#localaddr = ":7685"
localaddr = ":0"
resolveraddr = "[::1]:7777"
serverdomains = ["ubmedia", ""]
clientdomain = "ubmedia"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
iif = "https://localhost:8761/iiif/3"
concurrency = 3

[servertls]
type = "dev"

[clienttls]
type = "dev"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="mediaserverviewer"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
ca=["certs/ca.crt"]
interval="1h"
