#localaddr = ":7685"
localaddr = ":0"
resolveraddr = "[::1]:7777"
domains = ["ubmedia"]
#domains = ["ubmedia", "mediathek"]
instance = "ubviewer"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
iif = "https://localhost:8761/iiif/3"
concurrency = 3

[server]
type = "minivault"
initialtimeout = "1h"
[server.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dd2f1933f4bf79b.70e65cc35470d195" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "server_cert"
tokenpolicies = ["instance_ubviewer.mediaserveraction"]
tokeninterval = "48h"
tokenttl = "96h"
certtype = "server_cert"
dnss = ["instance_ubviewer.mediaserverproto.Action"]
uris = []
ips = []
certinterval = "24h"
certttl = "48h"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[client]
type = "minivault"
initialtimeout = "1h"
[client.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dd2f1933f4bf79b.70e65cc35470d195" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "client_cert"
tokenpolicies = ["instance_ubviewer.mediaserveraction"]
tokeninterval = "48h"
tokenttl = "96h"
certtype = "client_cert"
dnss = []
uris = [
    "grpc:miniresolverproto.MiniResolver",
    "grpc:ubmedia.mediaserverproto.Database",
    "grpc:mediathek.mediaserverproto.Database",
    "grpc:ubmedia.mediaserverproto.ActionDispatcher",
    "grpc:mediathek.mediaserverproto.ActionDispatcher"]
ips = []
certinterval = "24h"
certttl = "48h"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="ubviewer"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
